"""Added the Movie Table

Revision ID: 193922e0982f
Revises: f1c294f8c4a3
Create Date: 2025-01-24 22:04:04.217996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '193922e0982f'
down_revision = 'f1c294f8c4a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('repeat', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('finish', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('start', sa.DateTime(), nullable=True))
        batch_op.drop_column('release')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release', sa.DATETIME(), nullable=False))
        batch_op.drop_column('start')
        batch_op.drop_column('finish')
        batch_op.drop_column('repeat')
        batch_op.drop_column('progress')

    # ### end Alembic commands ###
