"""Added

_plot_and_release

Revision ID: 5c15f78b9bab
Revises: bb49040a876d
Create Date: 2025-04-15 21:09:13.410372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c15f78b9bab'
down_revision = 'bb49040a876d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plot', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('release', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('release')
        batch_op.drop_column('plot')

    # ### end Alembic commands ###
