"""Added the notes column to the Movie Table

Revision ID: 66dfb3ec6db0
Revises: 193922e0982f
Create Date: 2025-01-24 22:52:12.764197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66dfb3ec6db0'
down_revision = '193922e0982f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
