"""added relationship

Revision ID: bb49040a876d
Revises: 66dfb3ec6db0
Create Date: 2025-01-25 10:27:16.577723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb49040a876d'
down_revision = '66dfb3ec6db0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=False))
        batch_op.create_foreign_key('movie_owner_username', 'user', ['username'], ['username'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_constraint('movie_owner_username', type_='foreignkey')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
